#r "..\sharedlibs\MabService.dll"
#r "..\sharedlibs\MabService.Data.dll"
#r "..\sharedlibs\MabService.Shared.dll"
#r "..\sharedlibs\MabService.FunctionsHelper.dll"
#r "..\sharedlibs\Jint.dll"
#r "..\sharedlibs\MabService.JsLanguageBinding.dll"
